Q1: Create two numpy arrays and add the elements of both the arrays and store the result in 
sumArray.

DESCRIPTION:
    "
We have to create two numpy arrays and add the elements of both the arrays by using "np.add" as sum array. Now, we have to print the sum array. 

In [ ]:
import numpy as np
x1 = np.array([0, 1, 2, 3])
x2 = np.array([4, 5, 6, 7])
sum = np.add(x1, x2)
print("x1:", x1)
print("x2:", x2)
print("sum:", sum)

    OUTPUT:
        
        x1: [0 1 2 3]
        x2: [4 5 6 7]
        sum: [ 4  6  8 10]

Q2: Create a 3X3 array having values from 10-90(interval of 10) and store that in array1. Perform 
the following tasks:
a. Extract the 1st row from the array.
b. Extract the last element from the array.

DESCRPTION:
    
We have to create a 3x3 array having values from 10 to 90 (interval of 10) by using "np.squeeze(np.asarray)". we have to print 1st row from the array and the last element of the array.

In [5]:
import numpy as np
x = [[30*y + 10*x for x in range(1, 4)] for y in range(3)]
x = np.squeeze(np.asarray(x))
print(x)
print(x[:1])
print(x[2][2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[10 20 30]]
90


OUTPUT:
    
    [[10 20 30]
     [40 50 60]
     [70 80 90]]
    [[10 20 30]]
    90